---
apiVersion: aicc/v1
kind: Component
metadata:
  name: aicc-analyzer
  namespace: aicc
  version: 0.1.0
  description: Analyzer Service for Contract Compliance Evaluation Platform
  component_shortname: aicc-analyzer
  environment: prod
  owner: AICC_Team
  appcode: aicc-analyzer

spec:
  aws:
    account_id: "106573904847"
    rolenames:
      - aicc-analyzer-role-prod
      - aicc-analyzer-task-role-prod
    alb:
      app_healthcheck_path: /analyzer/health
      app_context_path: /analyzer/*
      healthy_threshold: 3
      unhealthy_threshold: 2
    regions:
      - region: us-east-1
        subnets:
          - subnet-0de1d95fcab5482d9
          - subnet-012cdc86dd7cdb070
        security_groups:
          - sg-027c05e94fb382c8

  environment_variables:
    DT_TAGS: "env:prod region:us-east-1 AppCode:aicc-analyzer AccountID:106573904847"
    DT_TENANT: "fs12101"
    DT_LOGLEVELCON: "warn"
    cluster_name: aicc-ecs-prod
    service_name: aicc-analyzer-prod
    task_cpu: 2048
    task_memory: 4096
    desired_count: 3
    container:
      name: aicc-analyzer-prod
      port: 8080
    ENVIRONMENT: prod
    DB_HOST_NAME_PORT: "aicc-analyzer-prod-rds-cluster.cluster-c0h2uoq1da.us-east-1.rds.amazonaws.com:5432"
    DB_NAME: "analyzer_db_prod"
    DB_USERNAME: "analyzer-prod-task-role"

  autoscaling:
    enabled: true
    min_capacity: 2
    max_capacity: 20
    target_cpu_utilization: 70
    target_memory_utilization: 75

  codedeploy:
    app_name: aicc-analyzer-prod
    deployment_group_name: aicc-analyzer-prod
    service_role_name: aicc-analyzer-codedeploy-role-prod
    strategy: BLUE_GREEN

  database:
    enable_db_migration: true
    migration_tool: "liquibase"
    host: "aicc-analyzer-prod-rds-cluster.cluster-c0h2uoq1da.us-east-1.rds.amazonaws.com"
    dbname: "analyzer_db_prod"
    schema: "analyzer_schema"
    username: "analyzer-prod-task-role"
    port: 5432
    region: us-east-1
    liquibase_changelog_file: "changelog-master.xml"

  sqs:
    analyzer_queue: aicc-analyzer-queue-prod
    status_queue: aicc-status-queue-prod
    audit_queue: aicc-audit-queue-prod
    dlq_max_receive_count: 3

  s3:
    contract_documents_bucket: aicc-contract-documents-prod
    documents_prefix: contract-docs/
    kms_encryption: true

  dynamodb:
    execution_state_table: evaluation_execution_state_prod
