---
apiVersion: aicc/v1
kind: Component
metadata:
  name: aicc-analyzer
  namespace: aicc
  version: 0.1.0
  description: Analyzer Service for Contract Compliance Evaluation Platform
  component_shortname: aicc-analyzer
  environment: feature
  owner: AICC_Team
  appcode: aicc-analyzer

spec:
  aws:
    account_id: "106573904847"
    rolenames:
      - aicc-analyzer-role-feature
      - aicc-analyzer-task-role-feature
    alb:
      app_healthcheck_path: /analyzer/health
      app_context_path: /analyzer/*
      healthy_threshold: 2
      unhealthy_threshold: 2
    regions:
      - region: us-east-1
        subnets:
          - subnet-0de1d95fcab5482d9
          - subnet-012cdc86dd7cdb070
        security_groups:
          - sg-027c05e94fb382c8

  environment_variables:
    DT_TAGS: "env:feature region:us-east-1 AppCode:aicc-analyzer AccountID:106573904847"
    DT_TENANT: "fs12101"
    DT_LOGLEVELCON: "debug"
    cluster_name: aicc-ecs-feature
    service_name: aicc-analyzer-feature
    task_cpu: 768
    task_memory: 1536
    desired_count: 1
    container:
      name: aicc-analyzer-feature
      port: 8080
    ENVIRONMENT: feature
    DB_HOST_NAME_PORT: "aicc-analyzer-feature-rds.cluster-c0h2uoq1da.us-east-1.rds.amazonaws.com:5432"
    DB_NAME: "analyzer_db_feature"
    DB_USERNAME: "analyzer-feature-task-role"

  autoscaling:
    enabled: false
    min_capacity: 1
    max_capacity: 3

  database:
    enable_db_migration: true
    migration_tool: "liquibase"
    host: "aicc-analyzer-feature-rds.cluster-c0h2uoq1da.us-east-1.rds.amazonaws.com"
    dbname: "analyzer_db_feature"
    schema: "analyzer_schema"
    username: "analyzer-feature-task-role"
    port: 5432
    region: us-east-1
    liquibase_changelog_file: "changelog-master.xml"

  sqs:
    analyzer_queue: aicc-analyzer-queue-feature
    status_queue: aicc-status-queue-feature
    audit_queue: aicc-audit-queue-feature
    dlq_max_receive_count: 2

  s3:
    contract_documents_bucket: aicc-contract-documents-feature
    documents_prefix: contract-docs/
    kms_encryption: true

  dynamodb:
    execution_state_table: evaluation_execution_state_feature
